/*
 * School21 OpenAPI Specification
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.izpz.edu;

import com.google.gson.*;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import okio.ByteString;

import java.io.IOException;
import java.io.StringReader;
import java.lang.reflect.Type;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;

/*
 * A JSON utility class
 *
 * NOTE: in the future, this class may be converted to static, which may break
 *       backward-compatibility
 */
public class JSON {
    private static Gson gson;
    private static boolean isLenientOnJson = false;
    private static DateTypeAdapter dateTypeAdapter = new DateTypeAdapter();
    private static SqlDateTypeAdapter sqlDateTypeAdapter = new SqlDateTypeAdapter();
    private static OffsetDateTimeTypeAdapter offsetDateTimeTypeAdapter = new OffsetDateTimeTypeAdapter();
    private static LocalDateTypeAdapter localDateTypeAdapter = new LocalDateTypeAdapter();
    private static ByteArrayAdapter byteArrayAdapter = new ByteArrayAdapter();

    private JSON() {}

    @SuppressWarnings("unchecked")
    public static GsonBuilder createGson() {
        return new GsonBuilder();
    }

    static {
        GsonBuilder gsonBuilder = createGson();
        gsonBuilder.registerTypeAdapter(Date.class, dateTypeAdapter);
        gsonBuilder.registerTypeAdapter(java.sql.Date.class, sqlDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(OffsetDateTime.class, offsetDateTimeTypeAdapter);
        gsonBuilder.registerTypeAdapter(LocalDate.class, localDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(byte[].class, byteArrayAdapter);
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.CampusV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.CampusesV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.ClusterMapV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.ClusterV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.ClustersV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.CoalitionV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.CoalitionsV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.ConditionRuleGroupV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.ConditionRuleV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.ConditionRuleValueV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.ConditionValueValueV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.CourseV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.ErrorResponseDTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.EventV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.EventsV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.GraphEdgeV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.GraphNodeItemV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.GraphNodeV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.GraphV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.ParticipantBadgeV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.ParticipantBadgesV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.ParticipantCampusV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.ParticipantCoalitionV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.ParticipantCourseV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.ParticipantCoursesV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.ParticipantFeedbackV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.ParticipantLoginsV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.ParticipantPointsV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.ParticipantProjectV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.ParticipantProjectsV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.ParticipantSkillV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.ParticipantSkillsV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.ParticipantV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.ParticipantWorkstationV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.ParticipantXpHistoryItemV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.ParticipantXpHistoryV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.ProjectV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.SaleV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.SalesV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.TeamMemberV1DTO.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ru.school21.edu.model.WorkplaceV1DTO.CustomTypeAdapterFactory());
        gson = gsonBuilder.create();
    }

    /**
     * Get Gson.
     *
     * @return Gson
     */
    public static Gson getGson() {
        return gson;
    }

    /**
     * Set Gson.
     *
     * @param gson Gson
     */
    public static void setGson(Gson gson) {
        JSON.gson = gson;
    }

    public static void setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
    }

    /**
     * Serialize the given Java object into JSON string.
     *
     * @param obj Object
     * @return String representation of the JSON
     */
    public static String serialize(Object obj) {
        return gson.toJson(obj);
    }

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T>        Type
     * @param body       The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(String body, Type returnType) {
        try {
            if (isLenientOnJson) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            if (returnType.equals(String.class)) {
                return (T) body;
            } else {
                throw (e);
            }
        }
    }

    /**
     * Gson TypeAdapter for Byte Array type
     */
    public static class ByteArrayAdapter extends TypeAdapter<byte[]> {

        @Override
        public void write(JsonWriter out, byte[] value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(ByteString.of(value).base64());
            }
        }

        @Override
        public byte[] read(JsonReader in) throws IOException {
            if (in.peek() == NULL) {
                in.nextNull();
                return new byte[0];
            } else {
                String bytesAsBase64 = in.nextString();
                ByteString byteString = ByteString.decodeBase64(bytesAsBase64);
                return byteString.toByteArray();
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 OffsetDateTime type
     */
    public static class OffsetDateTimeTypeAdapter extends TypeAdapter<OffsetDateTime> {

        private DateTimeFormatter formatter;

        public OffsetDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        }

        public OffsetDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, OffsetDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public OffsetDateTime read(JsonReader in) throws IOException {
            if (in.peek() == NULL) {
                in.nextNull();
                return null;
            }
            String date = in.nextString();
            if (date.endsWith("+0000")) {
                date = date.substring(0, date.length()-5) + "Z";
            }
            return OffsetDateTime.parse(date, formatter);
        }
    }

    /**
     * Gson TypeAdapter for JSR310 LocalDate type
     */
    public static class LocalDateTypeAdapter extends TypeAdapter<LocalDate> {

        private DateTimeFormatter formatter;

        public LocalDateTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE);
        }

        public LocalDateTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDate date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDate read(JsonReader in) throws IOException {
            if (in.peek() == NULL) {
                in.nextNull();
                return null;
            }
            String date = in.nextString();
            return LocalDate.parse(date, formatter);
        }
    }

    public static void setOffsetDateTimeFormat(DateTimeFormatter dateFormat) {
        offsetDateTimeTypeAdapter.setFormat(dateFormat);
    }

    public static void setLocalDateFormat(DateTimeFormatter dateFormat) {
        localDateTypeAdapter.setFormat(dateFormat);
    }

    /**
     * Gson TypeAdapter for java.sql.Date type
     * If the dateFormat is null, a simple "yyyy-MM-dd" format will be used
     * (more efficient than SimpleDateFormat).
     */
    public static class SqlDateTypeAdapter extends TypeAdapter<java.sql.Date> {

        private DateFormat dateFormat;

        public SqlDateTypeAdapter() {}

        public SqlDateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, java.sql.Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = date.toString();
                }
                out.value(value);
            }
        }

        @Override
        public java.sql.Date read(JsonReader in) throws IOException {
            if (in.peek() == NULL) {
                in.nextNull();
                return null;
            }
            String date = in.nextString();
            try {
                if (dateFormat != null) {
                    return new java.sql.Date(dateFormat.parse(date).getTime());
                }
                return new java.sql.Date(ISO8601Utils.parse(date, new ParsePosition(0)).getTime());
            } catch (ParseException e) {
                throw new JsonParseException(e);
            }
        }
    }

    /**
     * Gson TypeAdapter for java.util.Date type
     * If the dateFormat is null, ISO8601Utils will be used.
     */
    public static class DateTypeAdapter extends TypeAdapter<Date> {

        private DateFormat dateFormat;

        public DateTypeAdapter() {}

        public DateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = ISO8601Utils.format(date, true);
                }
                out.value(value);
            }
        }

        private Date parseDate(String date) throws JsonParseException, ParseException {
            if (dateFormat != null) {
                return dateFormat.parse(date);
            }
            return ISO8601Utils.parse(date, new ParsePosition(0));
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            try {
                if (in.peek() == NULL) {
                    in.nextNull();
                    return null;
                }
                String date = in.nextString();
                return parseDate(date);
            } catch (IllegalArgumentException e) {
                throw new JsonParseException(e);
            }
        }
    }

    public static void setDateFormat(DateFormat dateFormat) {
        dateTypeAdapter.setFormat(dateFormat);
    }

    public static void setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
    }
}
