{
 "title": "MainDashboard s21meet",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Most Active Users",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (user_id) (bot_button_press_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buttons by type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (bot_button_press_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buttons chart",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (button) (bot_button_press_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Pressed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(bot_button_press_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Buttons",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (button) (increase(bot_button_press_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "s21auth endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topk(10, \n  sum(rate(http_server_requests_seconds_count{job=\"s21auth\", uri!~\".*/actuator/.*\"}[1m])) \n  by (uri, method)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "s21bot endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "topk(10, \n  sum(rate(http_server_requests_seconds_count{job=\"s21bot\", uri!~\".*/actuator/.*\"}[1m])) \n  by (uri, method)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Common RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "s21edu endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "topk(10, \n  sum(rate(http_server_requests_seconds_count{job=\"s21edu\", uri!~\".*/actuator/.*\"}[1m])) \n  by (uri, method)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"}) by (job)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}