{
 "title": "MainDashboard s21meet",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "campus_name",
    "query": {
     "query": "label_values(edu_cluster_places_current, campus_name)"
    }
   },
   {
    "name": "cluster_name",
    "query": {
     "query": "label_values(edu_cluster_places_current{campus_name=~\"$campus_name\"}, cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "External API Calls [15m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (scheduler, client, operation, outcome) (\n  increase(edu_external_api_calls_total[15m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data parser duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "edu_scheduler_phase_last_duration_seconds{scheduler=\"campus_parser\",phase=\"participants\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "edu_scheduler_phase_last_duration_seconds{scheduler=\"campus_parser\",phase=\"clusters\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "edu_scheduler_phase_last_duration_seconds{scheduler=\"event_parser\",phase=\"get_events\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "sum by (phase, issue_type) (\n  increase(edu_scheduler_phase_issues_total{scheduler=\"campus_parser\"}[1h])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Occupied seats by campus",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (campus_name) (\n  edu_cluster_places_current{place_type=\"occupied\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Places by Cluster",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "sum by (cluster_name) (\n  edu_cluster_places_current{\n    campus_name=~\"$campus_name\",\n    cluster_name=~\"$cluster_name\",\n    place_type=\"occupied\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Campus parser errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 8 },
   "targets": [
    {
     "expr": "sum by (operation, reason) (\n  increase(edu_external_api_calls_total{scheduler=\"campus_parser\",outcome=\"error\"}[15m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "External API Errors By Reason (15m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "targets": [
    {
     "expr": "sum by (scheduler, client, operation, reason) (\n  increase(edu_external_api_calls_total{outcome=\"error\"}[15m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Most Active Users",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (user_id) (bot_button_press_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buttons chart",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (button) (bot_button_press_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buttons by type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (bot_button_press_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Pressed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(bot_button_press_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Events parser",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "edu_events_saved_last{scheduler=\"event_parser\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notify scheduler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "edu_notify_recipients_last{scheduler=\"notify_poller\",recipient_type=\"unique_users\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "edu_notify_recipients_last{scheduler=\"notify_poller\",recipient_type=\"deliveries\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buttons",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (button) (increase(bot_button_press_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "s21auth endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "topk(10, \n  sum(rate(http_server_requests_seconds_count{job=\"s21auth\", uri!~\".*/actuator/.*\"}[1m])) \n  by (uri, method)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "s21bot endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "topk(10, \n  sum(rate(http_server_requests_seconds_count{job=\"s21bot\", uri!~\".*/actuator/.*\"}[1m])) \n  by (uri, method)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Common RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "s21edu endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "topk(10, \n  sum(rate(http_server_requests_seconds_count{job=\"s21edu\", uri!~\".*/actuator/.*\"}[1m])) \n  by (uri, method)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"}) by (job)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}