server:
  port: 8083

spring:
  application:
      name: s21bot

bot:
  token: ${BOT_TOKEN}
  admin: ${BOT_ADMIN}
  group: ${BOT_GROUP}
  group-invite-link: ${BOT_GROUP_INVITE_LINK}

logging:
  level:
    io.github.resilience4j: INFO

rocketchat:
  service:
    url: ${ROCKETCHAT_SERVICE_URL}

profile:
  service:
    url: ${PROFILE_SERVICE_URL}