### Получить профиль по Telegram ID
POST http://localhost:8084/api/rocketchat/send
Content-Type: application/json

{
  "username": "quarkron",
  "message": "Привет! Это тестовая отправка через новый сервис."
}

