server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create  # Автоматически обновлять схему БД на основе сущностей
    show-sql: false  # Логирование SQL-запросов
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: false  # Форматировать SQL-запросы для удобства

edu:
  tokenEndpoint: http://localhost:8081/api/tokens/default

bot.service.url: http://localhost:8083

resilience4j:
  ratelimiter:
    instances:
      platform:
        limitForPeriod: 10
        limitRefreshPeriod: 100ms
        timeoutDuration: 1s
  retry:
    instances:
      platform:
        maxAttempts: 3
        waitDuration: 200ms

logging:
  level:
    io.github.resilience4j: INFO

api.client.enabled: true
cluster.api.enabled: true
profile:
  api.enabled: true
  service.enabled: true
participant.api.enabled: true
graphql.api.enabled: true
notify:
  service.enabled: true
  scheduler:
    enabled: true
    fixed-delay: PT30S
campus:
  api.enabled: true
  service.enabled: true
  scheduler:
    enabled: false
    fixed-delay: PT30S