server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Автоматически обновлять схему БД на основе сущностей
    show-sql: false  # Логирование SQL-запросов
    properties:
      hibernate:
        format_sql: false  # Форматировать SQL-запросы для удобства

edu:
  tokenEndpoint: http://localhost:8081/api/tokens/default

resilience4j:
  ratelimiter:
    instances:
      campusApi:
        limitForPeriod: 10
        limitRefreshPeriod: 100ms
        timeoutDuration: 1s

logging:
  level:
    io.github.resilience4j: INFO

notify.service.enabled: true
message.service.enabled: true
token.service.enabled: true
cluster.api.enabled: true
api.client.enabled: true
campus:
  api.enabled: true
  service.enabled: true