server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  h2:
    console:
      enabled: true
      path: /h2-console

token:
  scheduler:
    enabled: true
    refresh-delay: 30000

security:
  crypto:
    key-base64: ${CRYPTO_KEY_BASE64}

resilience4j:
  ratelimiter:
    instances:
      auth:
        limitForPeriod: 5
        limitRefreshPeriod: 1s
        timeoutDuration: 0
  retry:
    instances:
      auth:
        maxAttempts: 3
        waitDuration: 500ms

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG

edu:
  login: ${EDU_LOGIN}
  password: ${EDU_PASS}