global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "s21auth"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["s21auth:8081"]

  - job_name: "s21edu"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["s21edu:8082"]

  - job_name: "s21bot"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["s21bot:8083"]

  - job_name: "s21rocket"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["s21rocket:8084"]
