/*
 * School21 OpenAPI Specification
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.izpz.edu;

import com.google.gson.*;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonToken;
import com.google.gson.stream.JsonWriter;
import io.gsonfire.GsonFireBuilder;
import io.gsonfire.TypeSelector;

import okio.ByteString;

import java.io.*;
import java.lang.reflect.Type;
import java.text.DateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Map;

import static com.google.gson.stream.JsonToken.NULL;

/*
 * A JSON utility class
 *
 * NOTE: in the future, this class may be converted to static, which may break
 *       backward-compatibility
 */

public class JSON {
    private final Gson gson;

    public JSON() {
        gson = createGson().create();
    }

    public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder = new GsonFireBuilder();
        GsonBuilder builder = fireBuilder.createGsonBuilder();

        return builder
                .registerTypeAdapter(Date.class, new DateTypeAdapter())
                .registerTypeAdapter(OffsetDateTime.class, new OffsetDateTimeTypeAdapter())
                .registerTypeAdapter(LocalDate.class, new LocalDateTypeAdapter())
                .serializeNulls()
                .disableHtmlEscaping();
    }

    public Gson getGson() {
        return gson;
    }

    public <T> T deserialize(String json, Type type) {
        return gson.fromJson(json, type);
    }

    public <T> T deserialize(Reader reader, Type type) {
        return gson.fromJson(reader, type);
    }

    public static void setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
    }

    public String serialize(Object obj) {
        return gson.toJson(obj);
    }

    public String serialize(Object obj, Type type) {
        return gson.toJson(obj, type);
    }

    public <T> T deserialize(String json, Class<T> clazz) {
        return gson.fromJson(json, clazz);
    }

    public <T> T deserialize(Reader reader, Class<T> clazz) {
        return gson.fromJson(reader, clazz);
    }

    public <T> T deserialize(String json, Map<String, Class<?>> classByDiscriminatorValue, String discriminatorField) {
        JsonElement readElement = JsonParser.parseString(json);
        String discriminatorValue = getDiscriminatorValue(readElement, discriminatorField);
        Class<?> clazz = getClassByDiscriminator(classByDiscriminatorValue, discriminatorValue);
        @SuppressWarnings("unchecked")
        T result = (T) gson.fromJson(readElement, clazz);
        return result;
    }

    private static String getDiscriminatorValue(JsonElement readElement, String discriminatorField) {
        if (!readElement.isJsonObject() || !readElement.getAsJsonObject().has(discriminatorField)) {
            throw new IllegalArgumentException("Missing discriminator field: <" + discriminatorField + ">");
        }
        return readElement.getAsJsonObject().get(discriminatorField).getAsString();
    }

    private static Class<?> getClassByDiscriminator(Map<String, Class<?>> classByDiscriminatorValue, String discriminatorValue) {
        Class<?> clazz = classByDiscriminatorValue.get(discriminatorValue);
        if (clazz == null) {
            throw new IllegalArgumentException("Cannot determine model class of name: <" + discriminatorValue + ">");
        }
        return clazz;
    }

    // ===== DateTypeAdapter using java.time for ISO format =====

    private static class DateTypeAdapter extends TypeAdapter<Date> {
        private final DateTimeFormatter formatter = DateTimeFormatter.ISO_OFFSET_DATE_TIME;

        @Override
        public void write(JsonWriter out, Date value) throws IOException {
            if (value == null) {
                out.nullValue();
                return;
            }
            Instant instant = value.toInstant();
            out.value(formatter.format(instant.atOffset(ZoneOffset.UTC)));
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            if (in.peek() == JsonToken.NULL) {
                in.nextNull();
                return null;
            }
            String dateStr = in.nextString();
            OffsetDateTime odt = OffsetDateTime.parse(dateStr, formatter);
            return Date.from(odt.toInstant());
        }
    }

    private static class OffsetDateTimeTypeAdapter extends TypeAdapter<OffsetDateTime> {
        private final DateTimeFormatter formatter = DateTimeFormatter.ISO_OFFSET_DATE_TIME;

        @Override
        public void write(JsonWriter out, OffsetDateTime value) throws IOException {
            if (value == null) {
                out.nullValue();
                return;
            }
            out.value(formatter.format(value));
        }

        @Override
        public OffsetDateTime read(JsonReader in) throws IOException {
            if (in.peek() == JsonToken.NULL) {
                in.nextNull();
                return null;
            }
            String value = in.nextString();
            return OffsetDateTime.parse(value, formatter);
        }
    }

    private static class LocalDateTypeAdapter extends TypeAdapter<LocalDate> {
        private final DateTimeFormatter formatter = DateTimeFormatter.ISO_LOCAL_DATE;

        @Override
        public void write(JsonWriter out, LocalDate value) throws IOException {
            if (value == null) {
                out.nullValue();
                return;
            }
            out.value(formatter.format(value));
        }

        @Override
        public LocalDate read(JsonReader in) throws IOException {
            if (in.peek() == JsonToken.NULL) {
                in.nextNull();
                return null;
            }
            String value = in.nextString();
            return LocalDate.parse(value, formatter);
        }
    }

    public static void setOffsetDateTimeFormat(DateTimeFormatter dateFormat) {
        offsetDateTimeTypeAdapter.setFormat(dateFormat);
    }

    public static void setLocalDateFormat(DateTimeFormatter dateFormat) {
        localDateTypeAdapter.setFormat(dateFormat);
    }

    public static void setDateFormat(DateFormat dateFormat) {
        dateTypeAdapter.setFormat(dateFormat);
    }

    public static void setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
    }
}
