server:
  port: 8084

spring:
  application:
    name: s21rocket

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

rocketchat:
  websocket-uri: ${ROCKET_CHAT_URL}
  bot-username: ${ROCKET_CHAT_QR_BOT}
  token: ${ROCKET_CHAT_TOKEN}
  qr-timeout: ${ROCKET_CHAT_QR_TIMEOUT:30}
  message-timeout: ${ROCKET_CHAT_MESSAGE_TIMEOUT:15}