server:
  port: 8082
spring:
  datasource:
    url: ${DATA_SOURCE_URL}
    username: ${DATA_SOURCE_USERNAME}
    password: ${DATA_SOURCE_PASSWORD}
    driver-class-name: ${DATA_SOURCE_DRIVER}

  jpa:
    hibernate:
      ddl-auto: update  # Автоматически обновлять схему БД на основе сущностей
    show-sql: false  # Логирование SQL-запросов
    properties:
      hibernate:
        format_sql: false  # Форматировать SQL-запросы для удобства

edu:
  tokenEndpoint: "http://localhost:8080/api/tokens/default"

resilience4j:
  ratelimiter:
    instances:
      campusApi:
        limitForPeriod: 5
        limitRefreshPeriod: 100ms
        timeoutDuration: 1s


logging:
  level:
    io.github.resilience4j: INFO