name: Sonar Push

on:
  pull_request:
    branches:
      - master
    types:
      - closed
  workflow_dispatch:

concurrency:
  group: sonar-push-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  sonar-quality:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    name: Sonar Quality (push)
    uses: ./.github/workflows/sonar-common.yml
    with:
      sonar-host-url: ${{ vars.SONAR_HOST_URL }}
      sonar-organization: ${{ vars.SONAR_ORGANIZATION }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
