name: Test PR

on:
  pull_request:
    branches:
      - develop
      - master
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: test-pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  gradle-tests:
    uses: ./.github/workflows/_tests-reusable.yml
