name: Test Push

on:
  push:
    branches:
      - "feature/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: test-push-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gradle-tests:
    uses: ./.github/workflows/_tests-reusable.yml
